# Generated by Django 3.0.11 on 2021-01-02 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='address.Address', verbose_name='address_client'),
        ),
    ]
