# Generated by Django 3.0.11 on 2021-01-03 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210102_2156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_cashier',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_manager',
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Date time on wich the object was created', verbose_name='Creado el')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Date time on wich the object was modified', verbose_name='Modificado el')),
                ('date_of_birth', models.DateField(verbose_name='Fecha De Nacimiento')),
                ('entry_date', models.DateField(verbose_name='Fecha de entrada')),
                ('salary', models.FloatField(verbose_name='Sueldo')),
                ('is_manager', models.BooleanField(default=False, verbose_name='Gerente')),
                ('is_cashier', models.BooleanField(default=False, verbose_name='Cajero')),
                ('is_supervisor', models.BooleanField(default=False, verbose_name='Supervisor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user_employee')),
            ],
            options={
                'ordering': ['created', 'modified'],
                'get_latest_by': ['-created', '-modified'],
                'abstract': False,
            },
        ),
    ]
