# Generated by Django 3.0.11 on 2021-01-02 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50, verbose_name='País')),
                ('state', models.CharField(max_length=50, verbose_name='Estado')),
                ('street', models.CharField(max_length=50, verbose_name='Calle')),
                ('municipality', models.CharField(max_length=50, verbose_name='Municipio')),
            ],
        ),
    ]
